[package]
license = ["Apache-2.0"]
keywords = ["AI", "Cost/Paid"]
org = "ballerinax"
name = "openai.embeddings"
icon = "icon.png"
distribution = "2201.4.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
